### ISSUE TITLE
Access to PX4 folder

### ISSUE THREAD

**Issue by leanedonze** [open-airlab/VTNMPC-Autonomous-Wind-Turbine-Inspection#2]
Hi,

I wanted to see your simulation, but I cannot download the PX4 folder.

Would it be possible to give access to it?

Thanks

**Comment by abdelhakim96** [comment]
Hi leanedone.
Thank you for your interest in our simulation.
We have added the PX4 SITL simulation files inside the WTI_px4_modified folder. Please check it out :)
