### ISSUE TITLE
PX4 folder

### ISSUE THREAD

**Issue by martin24302** [open-airlab/VTNMPC-Autonomous-Wind-Turbine-Inspection#5]
Hi! The PX4 folder mentioned on step 3 in the ReadMe does not exist: [broken URL](https://drive.google.com/file/d/1BpnlglYMQI5q9lEwMCPNLGjPj5mzCoe5/view?usp=sharing)

**Comment by abdelhakim96** [comment]
Hi,

I have added it here:
https://github.com/open-airlab/VTNMPC-Autonomous-Wind-Turbine-Inspection/tree/main/Wind-Turbine-Inspection/WTI_px4_modified

please try this version.
